#include "basicdefines_A3.hpp"

class CfgPatches
{
	class USMilitaryPilot
	{
		units[]={"B_HelicrewUSA_F","B_HelipilotUSA_F"};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]={"A3_Characters_F","A3_Data_F","A3_Soft_F","A3_UI_F","A3_Anims_F_Config_Sdr","A3_Weapons_F","A3_Structures_F"};
	};
};

class CfgVehicles
{
	class B_Helipilot_F;
	class B_HelipilotUSA_F: B_Helipilot_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]={"veh_infantry_pilot_s"};
				speechPlural[]={"veh_infantry_pilot_p"};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_pilot_s";
		textPlural="$STR_A3_nameSound_veh_infantry_pilot_p";
		nameSound="veh_infantry_pilot_s";
		author="Flanker562";
		_generalMacro="B_HelicrewUSA_F";
		scope=2;
		side=1;
		faction="USA";
		identityTypes[]={"LanguageENG_F","Head_NATO","G_NATO_pilot"};
		displayName="US Army Heli Pilot";
		linkedItems[]=
		{
			"V_TacVest_blk",
			"H_PilotHelmetHeli_B",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_blk",
			"H_PilotHelmetHeli_B",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS",
			"NVGoggles_OPFOR"
		};
		weapons[]={"arifle_MX_Black_F","hgun_P07_F","Throw","Put"};
		respawnWeapons[]={"arifle_MX_Black_F","hgun_P07_F","Throw","Put"};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=160000;
		camouflage=2;
		modelSides[]={3,1};
		uniformClass="U_Multicam_ej";
		hiddenSelections[]={"camo"};
		hiddenSelectionsTextures[]={"\uh-60\Data\Uniforms\Mcamfs_co.paa"};
		role="Crewman";
		detectSkill=50;
	};
	class B_HelicrewUSA_F: B_Helipilot_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]={"veh_infantry_pilot_s"};
				speechPlural[]={"veh_infantry_pilot_p"};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_pilot_s";
		textPlural="$STR_A3_nameSound_veh_infantry_pilot_p";
		nameSound="veh_infantry_pilot_s";
		author="Flanker562";
		_generalMacro="B_HelicrewUSA_F";
		scope=2;
		side=1;
		faction="USA";
		identityTypes[]={"LanguageENG_F","Head_NATO","G_NATO_pilot"};
		displayName="US Army Heli Crew";
		linkedItems[]=
		{
			"V_TacVest_blk",
			"H_CrewHelmetHeli_B",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS",
			"ej_PVS15"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_blk",
			"H_CrewHelmetHeli_B",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS",
			"ej_PVS15"
		};
		weapons[]={"arifle_MX_Black_F","hgun_P07_F","Throw","Put"};
		respawnWeapons[]={"arifle_MX_Black_F","hgun_P07_F","Throw","Put"};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=160000;
		camouflage=2;
		modelSides[]={3,1};
		uniformClass="U_Multicam_ej";
		hiddenSelections[]={"camo"};
		hiddenSelectionsTextures[]={"\uh-60\Data\Uniforms\Mcamfs_co.paa"};
		role="Crewman";
		detectSkill=50;
	};
	class O_HelicrewRUS_F: B_Helipilot_F
	{
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]={"veh_infantry_pilot_s"};
				speechPlural[]={"veh_infantry_pilot_p"};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_pilot_s";
		textPlural="$STR_A3_nameSound_veh_infantry_pilot_p";
		nameSound="veh_infantry_pilot_s";
		author="Flanker562";
		_generalMacro="O_HelicrewRUS_F";
		scope=2;
		side=0;
		faction="RUSFED";
		identityTypes[]={"LanguageENG_F","Head_NATO","G_NATO_pilot"};
		displayName="Russian Heli Pilot";
		linkedItems[]=
		{
			"V_CarrierRigKBT_01_light_EAF_F",
			"H_PilotHelmetHeli_I_E",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"V_CarrierRigKBT_01_light_EAF_F",
			"H_PilotHelmetHeli_I_E",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS",
			"O_NVGoggles_grn_F"
		};
		weapons[]={"arifle_AK12U_F","Throw","Put","Binocular"};
		respawnWeapons[]={"arifle_AK12U_F","Throw","Put","Binocular"};
		magazines[]=
		{
			"30Rnd_762x39_AK12_Mag_F",
			"30Rnd_762x39_AK12_Mag_F",
			"30Rnd_762x39_AK12_Mag_F",
			"30Rnd_762x39_AK12_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_762x39_AK12_Mag_F",
			"30Rnd_762x39_AK12_Mag_F",
			"30Rnd_762x39_AK12_Mag_F",
			"30Rnd_762x39_AK12_Mag_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		cost=160000;
		camouflage=2;
		modelSides[]={3,1};
		uniformClass="U_B_RWGPilotCoveralls";
		hiddenSelections[]={"camo"};
		hiddenSelectionsTextures[]={"\uh-60\Data\Uniforms\coveralls_sandrus_co"};
		role="Crewman";
		detectSkill=50;
	};

};